rust: stable
language: rust

script:
  - cargo build 
  - cargo test 

matrix:
  include:
    - os: linux
      env: TARGET=i686-unknown-linux-musl
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      env: TARGET=x86_64-apple-darwin

before_deploy:
  - cargo build --release --target $TARGET
  - cp target/${TARGET}/release/hello-cicd hello-cicd-${TRAVIS_TAG}-${TARGET}
      
deploy:
  api_key:
    secure: "tBj3FAbnxcpp9J3fw4JndVU0o4CrWa3MLI6LOxOjyYMWAiG7BhEKVerFB2JLWoFruSMb9z3D4Ee9ZCQTuFTKWdEiQCYfpBD6+EU12ZIkNH5w++rG1he3eogBOew3a2+NoMr38AOK+OGTxxjEARiUmD/nmIuXHZCmxwcAjK0T/iVCtQRDYV9Fj9Nc23ou7eTxJhVvpDzdKglgfpHHPv9vAzL15XTsz//4kQ9VALKm4N2UUAO5ONOxQUvoziMDAhH5dOsPxeBe8lv4zYGGvKI0ksW0Eah9YK/oYVEX7/yfWrbfGWukvrEmsAY9WNLlR5ZHaSaneeCqIX191aLSijykd5uPINuDaoar8ZpORgGEsJ9GTByrO6hmOif9rBG2pwBbpw4QbIYoNY26I3Su2qtoRFkXTOnajhU2Uc2YMdGk1lfOLlt8MnClEEIGPjfg4bAQJnnD2bstp+ZSMv2Ls1s5MlZezJsBzTtn3Kdzi8AeMyCEX9GtnjEb46ehCYFx+DU8Y2SOfpTHahvkSLGdzOCIszyqFRVyEW5BBhI4I1xa83rEOARjJ4B423TvO68+0mp+F/loD9ReN66mWjh+7gu07YHrGcBiP36eAz3zF8lYQymCZiiUIc+6dM+ceq1vaEeJI3MqQPEHPIBBueuoEJi1IPRYQzeAiR3JjNgbYCVTbS8="

  file: hello-cicd-${TRAVIS_TAG}-${TARGET}

  on:
    tags: true

  provider: releases
  skip_cleanup: true
  
branches:
  only:
    # Pushes and PR to the master branch
    - master
    # Ruby regex to match tags.
    # Required, or travis won't trigger deploys when a new tag is pushed.
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    
notifications:
  email:
    on_success: never

